### PR TITLE
update Magisk

### PR DESCRIPTION
**Pull request by ayasa520**

### CODE REVIEW

**Comment by ayasa520** [comment]
image

**Comment by LegacyGamerHD** [comment]
thank you very much

**Comment by astroty** [comment]
Hey, I ran the script just fine without errors and magisk app shows up in the app menu but it says that magisk isn't installed

**Comment by ayasa520** [comment]
> Hey, I ran the script just fine without errors and magisk app shows up in the app menu but it says that magisk isn't installed

Could you try fresh install

**Comment by astroty** [comment]
This was a fresh anbox install
Right now I'm using Waydroid on Arch Linux
The steps I did were to run waydroid init -s GAPPS -f (and also without to test), then I started the waydroid-container.service then I started waydroid session. It shows the application up in the drawer but it says magisk isn't installed.

**Comment by LegacyGamerHD** [comment]
Works fine for me

**Comment by LegacyGamerHD** [comment]
> This was a fresh anbox install Right now I'm using Waydroid on Arch Linux The steps I did were to run waydroid init -s GAPPS -f (and also without to test), then I started the waydroid-container.service then I started waydroid session. It shows the application up in the drawer but it says magisk isn't installed.

Try restarting your PC

**Comment by astroty** [comment]
Well, I tried out with another kernel and it somehow worked
Currently I am using Liquorix (Doesn't work) and tried out Xanmod (which works). So I'm unsure what difference they have that specifically made it work.

**Pull request merged**
